# Generated by Django 5.2.7 on 2025-10-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphapayapp', '0003_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_att',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
