# Generated by Django 5.2.7 on 2025-11-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphapayapp', '0005_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
