# Generated by Django 5.2.7 on 2025-11-13 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphapayapp', '0006_alter_user_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_att', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alphapayapp.client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alphapayapp.manager')),
            ],
        ),
    ]
