# Generated by Django 5.2.7 on 2025-12-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientbank', '0004_credit_creditrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='invoice',
        ),
    ]
