# Generated by Django 5.2.7 on 2025-12-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientbank', '0006_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
