# Generated by Django 5.2.7 on 2025-12-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientbank', '0007_invoice_closed_invoice_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
