# Generated by Django 5.2.7 on 2025-12-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientbank', '0008_invoice_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='type',
            field=models.CharField(blank=True, choices=[('Saldo', 'Saldo'), ('Crédito', 'Crédito')], default='Saldo', max_length=50, null=True),
        ),
    ]
