# Generated by Django 5.2.7 on 2026-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processando'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='processing', max_length=20),
        ),
    ]
